# Generated by Django 5.0.1 on 2024-01-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divvy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='payedBy',
            new_name='paidBy',
        ),
    ]
